#!/bin/sh
echo "code formatting by clang-format"
clang-format -i \
             ./otimapp/include/*.hpp \
             ./otimapp/src/*.cpp \
             ./tests/*.cpp \
             ./app.cpp \
             ./app_random.cpp
for FILE in `git diff --staged --name-only`; do
    git add $FILE
done
echo "formatting done"
